//HDMI screen
HDMI_HOLES_LENGTH=157;
HDMI_HOLES_WIDTH=108;

//Back plate
BACK_PLATE_THICKNESS=3;

CIRCUIT_BOARD_SCREWSTANDARD0=2;

//Adapter0
CIRCUIT_BOARD_ADAPTER0_SPACING=10;
CIRCUIT_BOARD_ADAPTER0_SCREW_HEIGHT=6-BACK_PLATE_THICKNESS;
CIRCUIT_BOARD_ADAPTER0_SCREW_TRAP_HEIGHT=1.6;
CIRCUIT_BOARD_ADAPTER0_PLUS_WIDTH=5;